// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaKDxUs7q0Z4CGw1qm2fnIA2waSyFwVM',
    appId: '1:193793897751:android:655eda75bfe97277faf352',
    messagingSenderId: '193793897751',
    projectId: 'reachu-9a393',
    storageBucket: 'reachu-9a393.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEKTnBHHdxujHIEHGiw9NEIuhBHMP6-qg',
    appId: '1:193793897751:ios:7acefd5468082185faf352',
    messagingSenderId: '193793897751',
    projectId: 'reachu-9a393',
    storageBucket: 'reachu-9a393.firebasestorage.app',
    iosBundleId: 'com.example.reachuDriver',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmfct5R0CgYEv7fr8ltEGrBsPWB_gakM',
    appId: '1:193793897751:web:7b3c2dc785542d86faf352',
    messagingSenderId: '193793897751',
    projectId: 'reachu-9a393',
    authDomain: 'reachu-9a393.firebaseapp.com',
    storageBucket: 'reachu-9a393.firebasestorage.app',
    measurementId: 'G-SSD25XXTM3',
  );
}
